CREATE TABLE "blockstacks" (
  "id" bigserial PRIMARY KEY,
  "pos_id" INTEGER GENERATED BY DEFAULT AS IDENTITY DEFAULT (0),
  "tag" varchar NOT NULL,
  "text" varchar NOT NULL,
  "creation_date" timestamp DEFAULT (now())
);

CREATE INDEX ON "blockstacks" ("pos_id");

CREATE INDEX ON "blockstacks" ("creation_date");

CREATE INDEX ON "blockstacks" ("tag");
